CREATE TABLE Colaborador (
	ColaboradorId	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Usuario	VARCHAR(200) NOT NULL,
	Senha	INTEGER NOT NULL,
	Nome	VARCHAR(200) NOT NULL,
	NomeCompleto	VARCHAR(200),
	Apelido	VARCHAR(50),
	CPF	VARCHAR(14),
	RG	VARCHAR(20),
	DataAdmissao	DATETIME NOT NULL,
	DataDemissao	DATETIME,
	DataCadastro	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DataAlteracao	DATETIME
)