CREATE TABLE MaodeObra (
	MaodeObraId	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	MaodeObra	VARCHAR(500) NOT NULL DEFAULT '',
	Tipo	VARCHAR(100) NOT NULL DEFAULT '',
	Valor	DECIMAL(10,2) NOT NULL DEFAULT 0,
	VigenciaInicial	DATETIME NOT NULL DEFAULT '',
	VigenciaFinal	DATETIME NOT NULL DEFAULT '',
	Ativo	BIT NOT NULL DEFAULT 1,
	DataCadastro	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)