CREATE TABLE Veiculo (
	VeiculoId	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Marca	VARCHAR ( 200 ) NOT NULL DEFAULT '',
	Modelo	VARCHAR ( 200 ) NOT NULL DEFAULT '',
	VeiculoAtivo	BIT NOT NULL DEFAULT 1,
	DataCadastro	DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
)