CREATE TABLE Peca (
	PecaId	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Peca	VARCHAR ( 500 ) NOT NULL DEFAULT '',
	Fornecedor	VARCHAR ( 500 ) NOT NULL DEFAULT '',
	Valor	DECIMAL ( 8 , 2 ) NOT NULL DEFAULT 0,
	ValorFrete	DECIMAL ( 8 , 2 ) NOT NULL DEFAULT 0,
	Ativo	BIT NOT NULL DEFAULT 1,
	DataCadastro	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)